////////


#cmakedefine01 INCLUDE__STM32CUBEF2_EXTENSION

#if (INCLUDE__STM32CUBEF2_EXTENSION == 1)

#cmakedefine01 STM32CUBEF2__DTTY_STM32_UART_ENABLE

#endif /* (INCLUDE__STM32CUBEF2_EXTENSION == 1) */

